# Chapter1. 헬로 파이썬

1.3 파이썬 인터프리터

1.3.1 산술 연산 

In [1]:
1-2

-1

In [2]:
4*5

20

In [3]:
7/5

1.4

In [4]:
3 ** 2

9

1.3.2 자료형

In [5]:
type(10)

int

In [6]:
type(2.718)

float

In [7]:
type("hello")

str

1.3.3 변수

In [8]:
x=10
print(x)

10


In [9]:
x=100
print(x)

100


In [10]:
y=3.14
x*y

314.0

In [11]:
type(x*y)

float

1.3.4 리스트

In [23]:
a = [1, 2, 3, 4, 5]
print(a)

[1, 2, 3, 4, 5]


In [24]:
len(a)   #리스트의 길이 출력

5

In [25]:
a[0]     #첫 원소에 접근

1

In [26]:
a[4]     #다섯 번째 원소에 접근

5

In [27]:
a[4] = 99  #값 대입

In [28]:
print(a)

[1, 2, 3, 4, 99]


In [30]:
#슬라이싱
a[0:2]

[1, 2]

In [31]:
a[1:]

[2, 3, 4, 99]

In [32]:
a[:3]

[1, 2, 3]

In [33]:
a[:-1]   #처음부터 마지막 원소의 1개 앞까지 얻기

[1, 2, 3, 4]

In [34]:
a[:-2]   #처음부터 마지막 원소의 2개 앞까지 얻기

[1, 2, 3]

1.3.5 딕셔너리

In [35]:
# 딕셔너리 : key와 value를 한 쌍으로 저장
me = {'height':180}   #딕셔너리 생성
me['height']   #원소에 접근

180

In [36]:
me['weight'] = 70   #새 원소 추가
print(me)

{'height': 180, 'weight': 70}


1.3.6 bool

In [37]:
# 파이썬에는 bool이라는 자료형이 있음!
# True or False
# and, or, not 연산자 사용 가능

hungry = True    #배가 고프다.
sleepy = False   #졸리지 않다.

In [38]:
type(hungry)

bool

In [39]:
not hungry

False

In [40]:
hungry and sleepy

False

In [41]:
hungry or sleepy

True

1.3.7 if문

In [43]:
hungry = True
if hungry:
    print("I'm hungry")    #보통 tap 대신 4개의 공백 문자가 일반적.

I'm hungry


In [44]:
hungry = False
if hungry:
    print("I'm hungry")    
else:
    print("I'm not hungry")
    print("I'm sleepy")

I'm not hungry
I'm sleepy


1.3.8 for문

In [45]:
for i in[1, 2, 3]:
    print(i)

1
2
3


1.3.9 함수

In [46]:
def hello():
    print("Hello world!")
    
hello()

Hello world!


In [48]:
def hello(object):
    print("Hello " + object + "!")
    
hello("cat")

Hello cat!


1.4 파이썬 스크립트 파일

1.4.2 클래스

In [49]:
class Man:
    def __init__(self, name):    # 생성자
        self.name = name
        print("Initialized!")
        
    def hello(self):             # 메서드 1
        print("Hello " + self.name + "!")
        
    def goodbye(self):           # 메서드 2
        print("Good-bye " + self.name + "!")
        
m = Man("David")
m.hello()
m.goodbye()

Initialized!
Hello David!
Good-bye David!


1.5 넘파이

1.5.1 넘파이 가져오기

In [50]:
import numpy as np

1.5.2 넘파이 배열 생성하기

In [51]:
x = np.array([1.0, 2.0, 3.0])
print(x)

[1. 2. 3.]


In [52]:
type(x)

numpy.ndarray

1.5.3 넘파이의 산술 연산

In [53]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
x + y    # 원소별 덧셈

array([3., 6., 9.])

In [54]:
x - y

array([-1., -2., -3.])

In [55]:
x * y

array([ 2.,  8., 18.])

In [56]:
x / y

array([0.5, 0.5, 0.5])

여기서 주의할 점은 배열 x와 y의 원소 수가 같다는 것입니다.
x와 y의 원소 수가 같다면 산술 연산은 각 원소에 대해서 행해집니다.
원소 수가 다르면 오류가 발생하니 원소 수 맞추기는 중요하답니다.

In [57]:
# 스칼라값의 산술 연산도 가능 (브로드캐스트 기능)
x / 2.0

array([0.5, 1. , 1.5])

1.5.4 넘파이의 N차원 배열

In [58]:
# 2차원 배열
A = np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [59]:
A.shape

(2, 2)

In [60]:
A.dtype

dtype('int32')

In [61]:
B = np.array([[3, 0], [0, 6]])
A + B

array([[ 4,  2],
       [ 3, 10]])

In [62]:
A * B

array([[ 3,  0],
       [ 0, 24]])

In [63]:
# 배열과 마찬가지로 행렬과 스칼라값의 산술 연산도 가능 (브로드캐스트 기능)
A * 10

array([[10, 20],
       [30, 40]])

1.5.5 브로드캐스트

넘파이에서는 형상이 다른 배열끼리도 계산이 가능하다.

In [64]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
A * B

array([[10, 40],
       [30, 80]])

1.5.6 원소 접근

In [75]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [76]:
X[0]    # 0행

array([51, 55])

In [77]:
X[0][1]    # (0,1) 위치의 원소

55

In [78]:
# for문으로 각 원소에 접근하기
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


In [79]:
# 인덱스를 배열로 지정해 한 번에 여러 원소에 접근하기
X = X.flatten()    # X를 1차원 배열로 변환 (평탄화)
print(X)

[51 55 14 19  0  4]


In [80]:
X[np.array([0, 2, 4])]    # 인덱스가 0, 2, 4인 원소 얻기

array([51, 14,  0])

In [81]:
X > 15    #배열 X에서 15 이상인 값만 구하기

array([ True,  True, False,  True, False, False])

In [82]:
X[X>15]

array([51, 55, 19])